export const GET_MENU_LIST_REQUEST = "GET_MENU_LIST_REQUEST";
export const SET_MENU_LIST = "SET_MENU_LIST";
export const SET_SELETED_ITEM = "SET_SELETED_ITEM";
export const GET_LIST_ROUTES_REQUEST = "GET_LIST_ROUTES_REQUEST";
export const SET_LIST_ROUTES = "SET_LIST_ROUTES";
export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const SET_USER_LIST = "SET_USER_LIST";
